apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx
  namespace: istio-system
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - http://localhost:8082
